name: Data Job Hunter

on:
  schedule:
    # Runs at 17 minutes past every hour to avoid GitHub's peak traffic
    - cron: '17 * * * *'
  workflow_dispatch: # Allows you to run it manually anytime

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Crucial: Allows the bot to save jobs.json

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/checkout@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install google-genai requests

      - name: Run Job Agent
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        run: python hunter.py

      - name: Commit and Push Results
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add jobs.json
          # Only commit if there are changes to avoid errors
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update jobs: $(date)" && git push)
